### ISSUE TITLE
Webfont Conversion

### ISSUE THREAD

**Issue by adeoh** [larsenwork/Gidole#30]
http://www.fontsquirrel.com/fonts/gidole

"The license for this font is the SIL OFL license. This license does not allow us to redistribute derivative versions of the font without wholesale name changes inside and out of the font. Until we figure out a reasonable method of delivering these to you and complying with the license, you will have to use the Webfont Generator yourself on these, renaming the fonts appropriately."

Apparently by terms of license FontSquirrel cannot provide your font's webfont kit. Was this intentional? Being an open-source project I don't believe it is, you may be interested in shooting FontSquirrel a tweet or mail about it.

**Comment by larsenwork** [comment]
Done that months ago - dunno why he haven't changed it.

**Comment by larsenwork** [comment]
Gidole is now dual licensed. I'll ping the fontsquirrel guy with the next update

**Comment by PatTheMav** [comment]
FYI - still not fixed, still not possible to embed on websites 😐..
